### ISSUE TITLE
[feature] record area of the website

### ISSUE THREAD

**Issue by kwladyka** [getgauge-contrib/taiko-screencast#10]
I have a website [ClojureScript form validation demo](https://kwladyka.github.io/form-validator-cljs/) and I want to record a GIF in Continuous Deployment.

The point is I want to have GIF showing only the form area with small margin around to make it looks good (vs whole website)
![image](https://user-images.githubusercontent.com/3903726/69209519-24f1b980-0b1d-11ea-924a-156114307514.png)

I would like to see solution for this need.

How can I solve it today?

PS I run Taiko first time today.

**Comment by nehashri** [comment]
@kwladyka This is not possible right now. Taiko uses Chrome Dev Tools protocol to communicate with chromium. The Chrome Dev Tools protocol doesn't have a way to screencast a part of the screen only right now. Until support for that is added in Chrome Dev Tools protocol, we will not be able to support this in Taiko as well.
