### ISSUE TITLE
unable to install taiko-screen cast on windows 10

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge-contrib/taiko-screencast#8]
I install Python too and provided an environment variable on my Windows 10 machine.
Path as provided in my environment variables are as follows 
PYTHON
C:\Users\hadusumi\AppData\Local\Programs\Python\Python37\python.exe

After running the npm install I get the below error. Please let me know if there is anything else that I need to do or is there anylink that I can follow in order to have the documentation done.

C:\WINDOWS\system32>npm install -g taiko-screencast

> canvas@2.6.0 install C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error socket hang up
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\hadusumi\AppData\Local\Programs\Python\Python37", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\hadusumi\\AppData\\Roaming\\npm\\node_modules\\taiko-screencast\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\hadusumi\\AppData\\Roaming\\npm\\node_modules\\taiko-screencast\\node_modules\\canvas\\build\\Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hadusumi\\AppData\\Roaming\\npm\\node_modules\\taiko-screencast\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko-screencast\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hadusumi\AppData\Roaming\npm-cache\_logs\2019-10-15T15_28_59_652Z-debug.log

**Comment by harimadusumilli** [comment]
My Node version is as below:
C:\WINDOWS\system32>node -v
v10.15.0

**Comment by zabil** [comment]
Please try instructions mentioned here https://github.com/felixrieseberg/windows-build-tools/issues/56#issuecomment-327419416

In your case.
```
npm config set python "C:\Users\hadusumi\AppData\Local\Programs\Python\Python37\python.exe"
```

This is mostly and issue with setting up python. Closing this as it is not exactly linked to something that can be fixed in Taiko. Please feel free to discuss this.
